services:
  - type: web
    name: blogwebsite
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn blogproject.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.9

databases:
  - name: blog-db
    databaseName: blogdb
    user: bloguser
    plan: free